name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Incrementa la versión semántica según los mensajes de commit
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    # Inicia sesión en Docker Hub
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

    # Construye la imagen de Docker con la nueva versión y la etiqueta 'latest'
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t krixsjdk/webhooks:$NEW_VERSION .
        docker build -t krixsjdk/webhooks:latest .

    # Sube las imágenes de Docker a Docker Hub
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push krixsjdk/webhooks:$NEW_VERSION
        docker push krixsjdk/webhooks:latest

    # Cierra sesión en Docker Hub
    - name: Logout from Docker Hub
      run: docker logout
